import os

CREDENTIALS_PATH = os.path.join("credentials.json")
LOGS_DIR = os.path.join("..", "logs")

SAMPLE_RATE = 16000
CHUNK_MS = 30
CHUNK_SIZE = int(SAMPLE_RATE * CHUNK_MS / 1000)
CHANNELS = 1

VAD_FRAME_DURATION = 30
VAD_PADDING = 300
VAD_THRESHOLD = 0.5
VAD_AGGRESSIVENESS = 1

SPEECH_LANGUAGE = "pl-PL"
TRANSLATION_SOURCE = "pl"
TRANSLATION_TARGET = "en"

GOOGLE_PROJECT_ID = "presentationtranslator"
